# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93e592aae523d77867fbc9f76393ce46ee8700cbde245e5650749771f2d2edae897a0415867ce68e9b3ad2832414582a89be5e6da720bd293aa0b6c4e8dd36c4

test:
  secret_key_base: 2616816420b9017f1349cd480652c08aa284430bcc06b3140f59b2e077fae2c708817bbd9bf3d61f045b66b0b9fa3cdb8e25d90507e7c28c7e1b1907c9a0338c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
